import { SynthPatchConfig, Preset } from '../types/synth';

export const DEFAULT_PATCH: SynthPatchConfig = {
  osc1: {
    enabled: true,
    wave: 'sawtooth',
    octave: 0,
    semi: 0,
    detune: -5,
    gain: 0.7,
    pan: -0.2,
  },
  osc2: {
    enabled: true,
    wave: 'square',
    octave: 0,
    semi: 7, // Fifth harmonic
    detune: 7,
    gain: 0.5,
    pan: 0.2,
  },
  sub: {
    enabled: true,
    wave: 'sine',
    octave: -1,
    gain: 0.35,
  },
  noise: {
    enabled: false,
    gain: 0.05,
  },
  filter: {
    enabled: true,
    type: 'lowpass',
    cutoff: 2400,
    resonance: 3.5,
    envAmount: 0.45,
    keyTracking: 0.5,
  },
  filterEnv: {
    attack: 0.05,
    decay: 0.6,
    sustain: 0.25,
    release: 0.4,
  },
  ampEnv: {
    attack: 0.02,
    decay: 0.4,
    sustain: 0.7,
    release: 0.35,
  },
  lfo: {
    enabled: true,
    wave: 'sine',
    rate: 3.5,
    depth: 0.2,
    target: 'cutoff',
  },
  arp: {
    enabled: false,
    mode: 'up',
    bpm: 120,
    rateDivision: '1/8',
    octaves: 2,
    gate: 0.75,
  },
  effects: {
    distortion: {
      enabled: false,
      type: 'soft',
      drive: 0.35,
      tone: 4500,
      mix: 0.3,
    },
    chorus: {
      enabled: true,
      rate: 1.2,
      depth: 0.45,
      feedback: 0.25,
      mix: 0.35,
    },
    delay: {
      enabled: true,
      time: 0.32,
      feedback: 0.4,
      damping: 3800,
      pingPong: true,
      mix: 0.28,
    },
    reverb: {
      enabled: true,
      decay: 2.2,
      preDelay: 0.02,
      damping: 6000,
      mix: 0.3,
    },
    eq: {
      enabled: true,
      lowGain: 2,
      midGain: -1,
      highGain: 3,
    },
  },
  master: {
    volume: 0.8,
    glide: 0.04,
    mode: 'poly',
  },
};

export const PRESETS: Preset[] = [
  {
    id: 'cyber-lead',
    name: '80s Synthwave Lead',
    category: 'Lead',
    description: 'Классический винтажный лид с широким стерео-хорусом и дилеем',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'sawtooth', octave: 0, semi: 0, detune: -6, gain: 0.75, pan: -0.25 },
      osc2: { enabled: true, wave: 'square', octave: 0, semi: 0, detune: 6, gain: 0.65, pan: 0.25 },
      sub: { enabled: true, wave: 'triangle', octave: -1, gain: 0.3 },
      filter: { enabled: true, type: 'lowpass', cutoff: 3200, resonance: 4, envAmount: 0.4, keyTracking: 0.7 },
      ampEnv: { attack: 0.01, decay: 0.3, sustain: 0.8, release: 0.25 },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: true, type: 'soft', drive: 0.25, tone: 5000, mix: 0.25 },
        chorus: { enabled: true, rate: 1.4, depth: 0.5, feedback: 0.3, mix: 0.4 },
        delay: { enabled: true, time: 0.28, feedback: 0.45, damping: 4500, pingPong: true, mix: 0.3 },
        reverb: { enabled: true, decay: 2.5, preDelay: 0.02, damping: 7000, mix: 0.35 },
      },
    },
  },
  {
    id: 'acid-bass',
    name: 'Acid 303 Resonator',
    category: 'Bass',
    description: 'Агрессивный аналоговый эсид-бас с высоким резонансом и овердрайвом',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'sawtooth', octave: -1, semi: 0, detune: 0, gain: 0.85, pan: 0 },
      osc2: { enabled: true, wave: 'square', octave: -1, semi: 0, detune: 3, gain: 0.5, pan: 0 },
      sub: { enabled: true, wave: 'square', octave: -2, gain: 0.5 },
      filter: { enabled: true, type: 'lowpass', cutoff: 800, resonance: 14, envAmount: 0.85, keyTracking: 0.4 },
      filterEnv: { attack: 0.01, decay: 0.25, sustain: 0.05, release: 0.15 },
      ampEnv: { attack: 0.005, decay: 0.3, sustain: 0.2, release: 0.1 },
      master: { volume: 0.85, glide: 0.08, mode: 'mono' },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: true, type: 'hard', drive: 0.65, tone: 3200, mix: 0.55 },
        chorus: { enabled: false, rate: 1, depth: 0.2, feedback: 0.1, mix: 0 },
        delay: { enabled: true, time: 0.2, feedback: 0.35, damping: 3000, pingPong: false, mix: 0.25 },
        reverb: { enabled: true, decay: 1.2, preDelay: 0.01, damping: 4000, mix: 0.2 },
      },
    },
  },
  {
    id: 'space-pad',
    name: 'Lush Deep Space Pad',
    category: 'Pad',
    description: 'Глубокий атмосферный пэд с плавным нарастанием и мерцающим фильтром',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'sawtooth', octave: 0, semi: 0, detune: -12, gain: 0.6, pan: -0.4 },
      osc2: { enabled: true, wave: 'triangle', octave: 0, semi: 7, detune: 12, gain: 0.6, pan: 0.4 },
      sub: { enabled: true, wave: 'sine', octave: -1, gain: 0.4 },
      noise: { enabled: true, gain: 0.03 },
      filter: { enabled: true, type: 'lowpass', cutoff: 1600, resonance: 2, envAmount: 0.3, keyTracking: 0.3 },
      filterEnv: { attack: 1.2, decay: 2.0, sustain: 0.6, release: 2.5 },
      ampEnv: { attack: 0.9, decay: 1.5, sustain: 0.85, release: 2.2 },
      lfo: { enabled: true, wave: 'sine', rate: 0.6, depth: 0.35, target: 'cutoff' },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: false, type: 'soft', drive: 0.1, tone: 4000, mix: 0 },
        chorus: { enabled: true, rate: 0.8, depth: 0.7, feedback: 0.4, mix: 0.55 },
        delay: { enabled: true, time: 0.45, feedback: 0.55, damping: 3000, pingPong: true, mix: 0.38 },
        reverb: { enabled: true, decay: 4.8, preDelay: 0.04, damping: 8000, mix: 0.55 },
      },
      master: { volume: 0.75, glide: 0.05, mode: 'poly' },
    },
  },
  {
    id: 'cosmic-pluck',
    name: 'Cosmic Crystal Pluck',
    category: 'Pluck',
    description: 'Звонкий кристальный щипковый звук с коротким затуханием и стерео-эхо',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'triangle', octave: 1, semi: 0, detune: 0, gain: 0.7, pan: -0.2 },
      osc2: { enabled: true, wave: 'sine', octave: 2, semi: 0, detune: 4, gain: 0.5, pan: 0.2 },
      sub: { enabled: false, wave: 'sine', octave: -1, gain: 0.2 },
      filter: { enabled: true, type: 'lowpass', cutoff: 4500, resonance: 5, envAmount: 0.7, keyTracking: 0.8 },
      filterEnv: { attack: 0.005, decay: 0.35, sustain: 0.02, release: 0.2 },
      ampEnv: { attack: 0.005, decay: 0.5, sustain: 0.05, release: 0.3 },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: false, type: 'soft', drive: 0.1, tone: 4000, mix: 0 },
        chorus: { enabled: true, rate: 2.2, depth: 0.3, feedback: 0.2, mix: 0.3 },
        delay: { enabled: true, time: 0.25, feedback: 0.5, damping: 6000, pingPong: true, mix: 0.42 },
        reverb: { enabled: true, decay: 3.0, preDelay: 0.01, damping: 9000, mix: 0.4 },
      },
      master: { volume: 0.85, glide: 0, mode: 'poly' },
    },
  },
  {
    id: 'vintage-keys',
    name: 'Warm Neo-Soul Keys',
    category: 'Keys',
    description: 'Теплые клавиши в духе винтажного электропианино с тремоло и сатурацией',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'triangle', octave: 0, semi: 0, detune: -3, gain: 0.7, pan: -0.1 },
      osc2: { enabled: true, wave: 'sine', octave: 1, semi: 0, detune: 3, gain: 0.45, pan: 0.1 },
      sub: { enabled: true, wave: 'sine', octave: -1, gain: 0.25 },
      filter: { enabled: true, type: 'lowpass', cutoff: 2200, resonance: 1.8, envAmount: 0.35, keyTracking: 0.6 },
      filterEnv: { attack: 0.02, decay: 0.8, sustain: 0.2, release: 0.4 },
      ampEnv: { attack: 0.01, decay: 0.9, sustain: 0.4, release: 0.45 },
      lfo: { enabled: true, wave: 'sine', rate: 4.8, depth: 0.2, target: 'amplitude' },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: true, type: 'soft', drive: 0.2, tone: 3500, mix: 0.2 },
        chorus: { enabled: true, rate: 1.0, depth: 0.4, feedback: 0.1, mix: 0.3 },
        delay: { enabled: true, time: 0.3, feedback: 0.25, damping: 2500, pingPong: false, mix: 0.2 },
        reverb: { enabled: true, decay: 1.8, preDelay: 0.01, damping: 5000, mix: 0.25 },
        eq: { enabled: true, lowGain: 3, midGain: 1, highGain: 1 },
      },
      master: { volume: 0.8, glide: 0.02, mode: 'poly' },
    },
  },
  {
    id: 'chiptune-8bit',
    name: '8-Bit Arcade Arp',
    category: 'FX',
    description: 'Ретро звучание аркадного автомата с биткрашером и быстрым арпеджиатором',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'square', octave: 0, semi: 0, detune: 0, gain: 0.8, pan: 0 },
      osc2: { enabled: true, wave: 'triangle', octave: 1, semi: 0, detune: 0, gain: 0.4, pan: 0 },
      sub: { enabled: false, wave: 'square', octave: -1, gain: 0.3 },
      filter: { enabled: true, type: 'lowpass', cutoff: 8000, resonance: 1.5, envAmount: 0.1, keyTracking: 0 },
      ampEnv: { attack: 0.002, decay: 0.15, sustain: 0.1, release: 0.05 },
      arp: { enabled: true, mode: 'up', bpm: 136, rateDivision: '1/16', octaves: 2, gate: 0.6 },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: true, type: 'bitcrush', drive: 0.7, tone: 6000, mix: 0.6 },
        chorus: { enabled: false, rate: 1, depth: 0.2, feedback: 0, mix: 0 },
        delay: { enabled: true, time: 0.18, feedback: 0.3, damping: 8000, pingPong: true, mix: 0.25 },
        reverb: { enabled: true, decay: 1.0, preDelay: 0, damping: 7000, mix: 0.15 },
      },
      master: { volume: 0.75, glide: 0, mode: 'mono' },
    },
  },
  {
    id: 'electric-guitar',
    name: 'Electric Rock Guitar',
    category: 'Solo',
    description: 'Перегруженная рок-гитара с плотным ламповым овердрайвом, сустейном и резонансным эквалайзером',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'sawtooth', octave: 0, semi: 0, detune: -4, gain: 0.75, pan: -0.15 },
      osc2: { enabled: true, wave: 'square', octave: 0, semi: 0, detune: 5, gain: 0.65, pan: 0.15 },
      sub: { enabled: true, wave: 'triangle', octave: -1, gain: 0.25 },
      noise: { enabled: false, gain: 0.02 },
      filter: { enabled: true, type: 'lowpass', cutoff: 3600, resonance: 4.2, envAmount: 0.45, keyTracking: 0.75 },
      filterEnv: { attack: 0.008, decay: 0.6, sustain: 0.45, release: 0.3 },
      ampEnv: { attack: 0.005, decay: 0.8, sustain: 0.7, release: 0.35 },
      lfo: { enabled: true, wave: 'sine', rate: 5.5, depth: 0.12, target: 'pitch' },
      arp: { enabled: false, mode: 'up', bpm: 120, rateDivision: '1/8', octaves: 1, gate: 0.8 },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: true, type: 'hard', drive: 0.75, tone: 4200, mix: 0.7 },
        chorus: { enabled: true, rate: 1.4, depth: 0.35, feedback: 0.2, mix: 0.28 },
        delay: { enabled: true, time: 0.28, feedback: 0.38, damping: 4200, pingPong: true, mix: 0.32 },
        reverb: { enabled: true, decay: 2.0, preDelay: 0.015, damping: 6500, mix: 0.3 },
        eq: { enabled: true, lowGain: 3, midGain: 3.5, highGain: 1.5 },
      },
      master: { volume: 0.8, glide: 0.045, mode: 'legato' },
    },
  },
  {
    id: 'solo-violin',
    name: 'Expressive Concert Violin',
    category: 'Solo',
    description: 'Певучая смычковая скрипка с естественным вибрато, атакой струны и акустикой концертного зала',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'sawtooth', octave: 0, semi: 0, detune: -5, gain: 0.75, pan: -0.2 },
      osc2: { enabled: true, wave: 'sawtooth', octave: 0, semi: 0, detune: 6, gain: 0.6, pan: 0.2 },
      sub: { enabled: false, wave: 'sine', octave: -1, gain: 0.1 },
      noise: { enabled: true, gain: 0.04 },
      filter: { enabled: true, type: 'lowpass', cutoff: 3200, resonance: 3.2, envAmount: 0.35, keyTracking: 0.85 },
      filterEnv: { attack: 0.09, decay: 0.8, sustain: 0.75, release: 0.45 },
      ampEnv: { attack: 0.07, decay: 0.6, sustain: 0.85, release: 0.4 },
      lfo: { enabled: true, wave: 'sine', rate: 5.4, depth: 0.22, target: 'pitch' },
      arp: { enabled: false, mode: 'up', bpm: 120, rateDivision: '1/8', octaves: 1, gate: 0.8 },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: true, type: 'soft', drive: 0.18, tone: 4800, mix: 0.18 },
        chorus: { enabled: true, rate: 0.9, depth: 0.45, feedback: 0.15, mix: 0.35 },
        delay: { enabled: true, time: 0.32, feedback: 0.25, damping: 4000, pingPong: true, mix: 0.22 },
        reverb: { enabled: true, decay: 3.6, preDelay: 0.03, damping: 8000, mix: 0.45 },
        eq: { enabled: true, lowGain: 0.5, midGain: 3.0, highGain: 2.0 },
      },
      master: { volume: 0.85, glide: 0.06, mode: 'legato' },
    },
  },
  {
    id: 'jazz-saxophone',
    name: 'Warm Jazz Saxophone',
    category: 'Solo',
    description: 'Бархатный джазовый саксофон с характерным дыханием трости, теплыми обертонами и блюзовым легато',
    config: {
      ...DEFAULT_PATCH,
      osc1: { enabled: true, wave: 'square', octave: 0, semi: 0, detune: -2, gain: 0.72, pan: -0.1 },
      osc2: { enabled: true, wave: 'sawtooth', octave: 0, semi: 0, detune: 4, gain: 0.48, pan: 0.1 },
      sub: { enabled: true, wave: 'sine', octave: -1, gain: 0.2 },
      noise: { enabled: true, gain: 0.05 },
      filter: { enabled: true, type: 'lowpass', cutoff: 2200, resonance: 4.5, envAmount: 0.42, keyTracking: 0.75 },
      filterEnv: { attack: 0.045, decay: 0.5, sustain: 0.6, release: 0.3 },
      ampEnv: { attack: 0.035, decay: 0.4, sustain: 0.8, release: 0.28 },
      lfo: { enabled: true, wave: 'sine', rate: 4.8, depth: 0.18, target: 'pitch' },
      arp: { enabled: false, mode: 'up', bpm: 120, rateDivision: '1/8', octaves: 1, gate: 0.8 },
      effects: {
        ...DEFAULT_PATCH.effects,
        distortion: { enabled: true, type: 'soft', drive: 0.24, tone: 3500, mix: 0.22 },
        chorus: { enabled: true, rate: 1.1, depth: 0.32, feedback: 0.15, mix: 0.25 },
        delay: { enabled: true, time: 0.24, feedback: 0.28, damping: 3200, pingPong: true, mix: 0.24 },
        reverb: { enabled: true, decay: 2.4, preDelay: 0.02, damping: 5500, mix: 0.36 },
        eq: { enabled: true, lowGain: 2.5, midGain: 4.0, highGain: -0.5 },
      },
      master: { volume: 0.82, glide: 0.04, mode: 'legato' },
    },
  },
];
